# This .travis.yml works to check "this" repository, namely `industrial_ci`.
# A template for users can be found here: https://github.com/ros-industrial/industrial_ci/blob/master/doc/.travis.yml

# Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic

git:
  quiet: true

env:
  matrix:
  - ROS_DISTRO=kinetic DOCKER_BASE_IMAGE=arm64v8/ros:kinetic-perception
  - ROS_DISTRO=kinetic DOCKER_IMAGE=arm64v8/ros:kinetic-perception

install:
  - sudo apt-get install qemu-user-static
  - docker run --rm --privileged multiarch/qemu-user-static --debian
  - cat /proc/sys/fs/binfmt_misc/qemu-aarch64
  - cat /proc/sys/fs/binfmt_misc/qemu-arm
script:
  - ./travis.sh
