# This .travis.yml works to check "this" repository, namely `industrial_ci`.
# A template for users can be found here: https://github.com/ros-industrial/industrial_ci/blob/master/doc/.travis.yml

# Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic

git:
  quiet: true

env:
  matrix:
  - ROS_DISTRO=kinetic DOCKER_BASE_IMAGE=arm64v8/ros:kinetic-perception INJECT_QEMU=aarch64
  - ROS_DISTRO=kinetic DOCKER_IMAGE=arm64v8/ros:kinetic-perception INJECT_QEMU=aarch64
  - ROS_DISTRO=kinetic DOCKER_IMAGE=arm32v7/ros:kinetic-perception INJECT_QEMU=arm
  - ROS_DISTRO=kinetic DOCKER_BASE_IMAGE=arm32v7/ros:kinetic-perception INJECT_QEMU=arm

install:
  - sudo apt-get install qemu-user-static
script:
  - ./travis.sh
