# This .travis.yml works to check "this" repository, namely `industrial_ci`.
# A template for users can be found here: https://github.com/ros-industrial/industrial_ci/blob/master/doc/.travis.yml

# Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic

git:
  quiet: true

env:
  matrix:
    - ROS_DISTRO=kinetic _EXTERNAL_REPO='github:ros-controls/ros_control#kinetic-devel' UPSTREAM_WORKSPACE="ros_control.rosinstall -ros_control -ros_controllers" VERBOSE_TESTS=true
    - ROS_DISTRO=kinetic _EXTERNAL_REPO='github:ros-controls/ros_control#kinetic-devel' UPSTREAM_WORKSPACE="ros_control.rosinstall -ros_control -ros_controllers"

script:
  - for i in {1..6}; do industrial_ci/_wrap_test.sh || exit $?; done
