# This .travis.yml works to check "this" repository, namely `industrial_ci`.
# A template for users can be found here: https://github.com/ros-industrial/industrial_ci/blob/master/doc/.travis.yml

# Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic

git:
  quiet: true

env:
  global:
    - POST_PROCESS='echo "post processing reached"'
    - DOCKER_BUIILD_OPTS="--build-arg http_proxy=http://172.17.0.1:3142" DOCKER_RUN_OPTS="-e http_proxy=http://172.17.0.1:3142"

  matrix:
    - ROS_DISTRO=indigo
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=melodic
    - ROS_DISTRO=dashing

script:
  - sudo apt-get install -qq -y apt-cacher-ng
  - industrial_ci/_wrap_test.sh # this script is only for internal use
