# This .travis.yml works to check "this" repository, namely `industrial_ci`.
# A template for users can be found here: https://github.com/ros-industrial/industrial_ci/blob/master/doc/.travis.yml

# Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic

git:
  quiet: true

env:
  global:
    - BEFORE_INIT="sed -i -e 's%http://archive.ubuntu.com/ubuntu%mirror://mirrors.ubuntu.com/mirrors.txt%' /etc/apt/sources.list"

  matrix:
    - ROS_DISTRO=indigo  ROS_REPO=main
    - ROS_DISTRO=kinetic ROS_REPO=main
    - ROS_DISTRO=melodic ROS_REPO=main
    - ROS_DISTRO=dashing ROS_REPO=main

script:
  - industrial_ci/_wrap_test.sh # this script is only for internal use
