#   This .travis.yml works to check "this" repository, namely `industrial_ci`. Do not get confused with the check of "client" repositories (repos that use travis configs in this repo).

#  Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

#sudo: required  # Not required by industrial_ci that uses Docker.
#dist: trusty    # Not required by industrial_ci that uses Docker.
services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic
env:
  matrix:
    - ROS_DISTRO=kinetic _EXTERNAL_REPO='ros/actionlib#indigo-devel' ROS_REPO=ros ABICHECK=true ABICHECK_URL=https://github.com/ros/actionlib/archive/hydro-devel.zip
script:
  - industrial_ci/_wrap_test.sh # this script is only for internal use
