# This .travis.yml works to check "this" repository, namely `industrial_ci`.
# A template for users can be found here: https://github.com/ros-industrial/industrial_ci/blob/master/doc/.travis.yml

# Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic

git:
  quiet: true


env:
  global:
    - ROS_DISTRO=kinetic _EXTERNAL_REPO='github:ros-industrial/industrial_core@kinetic-devel' AFTER_INSTALL_TARGET_DEPENDENCIES='rm -rf $target_ws/src/*'
  matrix:
    - ROS_REPO=main APT_PROXY=
    - ROS_REPO=main
    - ROS_REPO=testing APT_PROXY=
    - ROS_REPO=testing

script:
  - industrial_ci/_wrap_test.sh # this script is only for internal use
