name: 'ROS industrial_ci'
inputs:
  config:
    description: 'Configuration in JSON format, e.g. from matrix'
    required: false
runs:
  using: "composite"
  steps:
    - run: echo "$GITHUB_ACTION_PATH" && find "$GITHUB_ACTION_PATH"
      shell: bash
      env:
        INPUT_CONFIG: ${{ inputs.config }}
