name: 'ROS industrial_ci'
inputs:
  matrix:
    description: 'Matrix'
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/.github/action.sh
      shell: bash
      env:
        INPUT_MATRIX: ${{ inputs.matrix }}