name: Windows
on:
  push:
  pull_request:

jobs:
  industrial_ci:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: './'
        env:
          ROS_DISTRO: foxy
          OS_NAME: windows
          OS_CODE_NAME: 10.0.17763.1757
